# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejectedinfo',
            old_name='customer_id',
            new_name='cust',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='cust_id',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default='8921922302457'),
        ),
    ]
