# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160303_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='current_balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default='3642260258874'),
        ),
    ]
