# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 22:15
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20160303_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default='1280107892205'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(200.0)]),
        ),
    ]
