# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160304_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default='1822791638066'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_num',
            field=models.ForeignKey(db_column='account_number', on_delete=django.db.models.deletion.CASCADE, to='main.Account'),
        ),
    ]
