# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160304_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectedinfo',
            options={'ordering': ['-information']},
        ),
        migrations.AddField(
            model_name='rejectedinfo',
            name='attempted_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 7, 0, 6, 11, 956110, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default='8599317161349', unique=True),
        ),
    ]
